### ISSUE TITLE
SA1309 states that you shouldn't use underscores when naming fields

### ISSUE THREAD

**Issue by asser-dk** [MakingSense/code-style-guides#33]
I know this could turn into a tabs vs. spaces debate but here goes:

The C# style guide links to [SA1309](http://stylecop.soyuz5.com/SA1309.html) as a means to argue that you should name your private fields starting with underscore instead of using `this.` prefix, however; SA1309 (which name is `FieldNamesMustNotBeginWithUnderscore`) states that you should never use underscores for field names and you should in fact use the `this.` prefix instead.

Also; the [General Naming Convention](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions) for the .Net Platform Guide states: "X DO NOT use underscores, hyphens, or any other nonalphanumeric characters."

**Comment by mvazquez-ms** [comment]
Thanks for pointing out the inconsistency on this guide, we should clarify that _our_ preference is to have [SA1309 ](http://stylecop.soyuz5.com/SA1309.html) disabled. 

Also, the usage of  `.this` to differentiate private fields from vars is discouraged by [CA1500](https://msdn.microsoft.com/en-us/library/ms182216.aspx).

I usually prefer to stick to the standards, but in this particular case, my reasoning is similar to the accepted answer [here](https://stackoverflow.com/questions/3215395/ca1500-vs-sa1309-which-one-wins). 

Anyway, it's open for debate if someone has a different opinion. Any thoughts here guys?
(cc @matiasbeckerle , @AlphaGit , @andresmoschini , @afantini , @gastonmancini)

And thanks again for the feedback @asser-dk !

**Comment by matiasbeckerle** [comment]
Thank you very much @asser-dk!

When we placed the StyleCop reference links we wanted to provide ruleset/editorconfig/resharper references so anyone can customize as they want. We are actually providing some tentative [ruleset](https://github.com/MakingSense/code-style-guides/blob/master/CSharp/CSharpStyleguide.ruleset) and [.editorconfig](https://github.com/MakingSense/code-style-guides/blob/master/CSharp/.editorconfig) files.

As an example, for style SA1309 we use the value "none" (see https://github.com/MakingSense/code-style-guides/blob/master/CSharp/CSharpStyleguide.ruleset#L21) to match what is described here.

Internally in our latest projects we preferred to use the underscore, which is weird because is also being used on the released source code from Microsoft (dotnet, MVC).

But with your point I understand our purpose is not enough clear and we should do something about it so thanks!

**Comment by AlphaGit** [comment]
I agree with @mvazquez-ms: we currently prefer the underscore prefix for private members.

@asser-dk does make a good point, and as @matiasbeckerle mentioned, it is probably worth some clarification in our guide to indicate that such preference is intentional.

Thanks @asser-dk! You have a very keen eye!

**Comment by matiasbeckerle** [comment]
Thank you again. I've created the following ticket to improve the guide: https://github.com/MakingSense/code-style-guides/issues/35
